---
- hosts: all
  tasks:
    - name: clone tmux plugin
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: ~/.tmux/plugins/tpm
    - name: Make symlink for configuration
      file: src={{ item.src }} dest={{ item.dst }} state=link force=yes
      with_items:
          - { src: "{{ playbook_dir }}/tmux/tmux.conf", dst: '~/.tmux.conf' }
